### PR TITLE
[WORK IN PROGRESS] set up continuous integration

### LINKED ISSUE #20: add automated tests / continuous integration

### PR DESCRIPTION
**Pull request by afeld**
Closes #20.

### CODE REVIEW

**Comment by afeld** [comment]
Running into this issue:

https://discuss.circleci.com/t/docker-with-centos7-systemd-container/885

**Comment by afeld** [comment]
* [ ] Try out Test Kitchen /cc https://github.com/GSA/catalog-deploy/pull/202

**Comment by afeld** [comment]
* [ ] Simplify this to just do the validations; it's better than nothing, and we can figure out how to run the playbook in CI later

**Comment by JJediny** [comment]
@afeld found this example that's using docker in circleci to run playbooks https://circleci.com/gh/William-Yeh/ansible-nginx

Approach covered here:
https://github.com/kfitzpatrick/ansible-docker-circle

**Comment by JJediny** [comment]
closed by #40

**Pull request closed without merging**
