### PR TITLE
don't set up Ansible as part of the base install

### PR DESCRIPTION
**Pull request by afeld**
D2D, for example, installs Ansible via pip, so that we can more easily take advantage of new features. This change puts the onus on projects to install Ansible packages + plugins themselves, which isn't a huge burden.

Moved it to the `test` playbook, which is an example usage of the role.

### CODE REVIEW

**Comment by kishorebabu12** [comment]
Do we plan to build a standard script (shell script or something similar) for project teams to use to install Ansible+plugins?

**Comment by afeld** [comment]
Good question - not sure yet. May also change with #18, as then Ansible will be within containers, rather than on the master machine itself.

**Comment by kishorebabu12** [comment]
I like the idea of Ansible being part of the container. Should we wait until this solution is built or provide an interim solution (a simple standard script) for project teams to use to install Ansible_plugins?

**Comment by afeld** [comment]
No, you're right - let's stick with installing Ansible by default.

**Pull request closed without merging**
